[package]
name = "twitch_piramid_bot"
version = "0.1.0"
edition = "2021"
default-run = "twitch_piramid_bot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = {version = "0.13.1", features = ["toml"]}
governor = "0.5.0"
serde = "1.0.8"
rand = "0.8.5"
rocksdb = "0.19.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
twitch-irc = "5.0.0"

