[package]
name = "twitch_piramid_bot"
version = "0.1.0"
edition = "2021"
default-run = "twitch_piramid_bot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {version = "0.7.4", optional = true }
askama = {version = "0.12.1", optional = true }
async-trait = "0.1.77"
chrono = {version = "0.4.31", features = ["serde"]}
config = {version = "0.13.4", features = ["toml"]}
governor = "0.6.0"
futures-util = "0.3.30"
log = "0.4.20"
serde = "1.0.195"
serde_json = "1.0.111"
serde_regex = "1.1.0"
simple_logger = "4.3.3"
regex = "1.10.2"
rand = "0.8.5"
reqwest = { version = "0.11.23", features = ["json"] }
rocksdb = "0.21.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
toml = "0.8.8"
twitch-irc = { version = "5.0.1", features = ["transport-ws-native-tls", "refreshing-token-native-tls"] }
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }

[features]
web = ["axum", "askama"]

[[bin]]
name = "serve_pyramids"
required-features = ["web"]