[package]
name = "twitch_piramid_bot"
version = "0.1.0"
edition = "2021"
default-run = "twitch_piramid_bot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.2"
askama = "0.11"
async-trait = "0.1.68"
config = {version = "0.13.2", features = ["toml"]}
governor = "0.5.1"
futures-util = "0.3.15"
log = "0.4.17"
serde = "1.0.148"
serde_json = "1.0.91"
serde_regex = "1.1.0"
simple_logger = "4.0.0"
regex = "1.8.4"
rand = "0.8.5"
reqwest = { version = "0.11.13", features = ["json"] }
rocksdb = "0.19.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
toml = "0.5.9"
twitch-irc = { version = "5.0.0", features = ["transport-ws-native-tls", "refreshing-token-native-tls"] }
tokio-tungstenite = { version = "0.18.0", features = ["native-tls"] }
