name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: DigitalOcean Docker Image Publish
      # You may pin to the exact commit or the version.
      # uses: ripplr-io/docr-docker-publish@44fac8d6ff7c3ece58c9ffe50f370514d166f5b7
      uses: ripplr-io/docr-docker-publish@v1
      with:
        # Image path in the format registry-name/image-name
        image_path: jbrr/bot
        # Number of characters from the commit SHA
        # sha_size: # optional, default is 8
        # The path + name of the Dockerfile you want to build (-f flag)
        # dockerfile: # optional, default is Dockerfile
        # The docker build context (usually '.')
        # docker_build_context: # optional, default is .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIV_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd Projects/twitch_bot
            docker-compose stop
            docker-compose rm -f
            docker-compose pull
            docker-compose up -d